gorm:
  type: mysql
  host: mysql.hidevopsio
  port: 3306
  database: ${app.name:test}
  username: demo
  password: Duahbi3GqMmeS7ogPw743xtmsmVFiDIaNwh24BokqC1BnUIah8doCRRhVuIqtWs3tl8nHRNkEWMIbuKAo6GleN4FwSoO56B8HAxqP3Kv8Jr3A6L2bam1bglFJRDx6rRkSuX4zrO3D/35t1YSFdPKf+n2PWIEeEJI6zcULo7UVKA=
  charset: utf8
  parseTime: true
  loc: Asia/Shanghai
  config:
    decrypt: true

etcd:
  type: etcd
  dialTimeout: 5
  requestTimeout: 10
  endpoints: 172.16.10.47:2379
  cert:
    certFile: config/certs/etcd.pem
    keyFile: config/certs/etcd-key.pem
    trustedCAFile: config/certs/ca.pem