apiVersion: mio.io/v1alpha1
kind: BuildConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mio.io/v1alpha1","kind":"BuildConfig","metadata":{"annotations":{},"clusterName":"","creationTimestamp":"2018-11-05T08:29:13Z","generation":0,"name":"nodejs-8","namespace":"templates","resourceVersion":"116755105","selfLink":"/apis/mio.io/v1alpha1/namespaces/templates/buildconfigs/nodejs-8","uid":"e04355dd-e0d4-11e8-96de-005056935c80"},"spec":{"baseImage":"docker.vpclub.cn/hidevopsio/nodejs:8.12-alpine-0.0.1","cloneConfig":{"branch":"master","dstDir":"/opt/app-root/src/vpclub","url":"https://gitlab.vpclub.cn"},"codeType":"nodejs","compileCmd":[{"Script":"npm install","execType":"script"},{"Script":"npm run build:dev","execType":"script"},{"commandName":"pwd"}],"deployData":{"Envs":{"APP_PROFILES_ACTIVE":"local","CODE_TYPE":"nodejs","DOCKER_API_VERSION":"1.24","npm_config_disturl":"https://npm.taobao.org/dist/","npm_config_electron_mirror":"https://npm.taobao.org/mirrors/electron/","npm_config_phantomjs_cdn":"https://npm.taobao.org/dist/phantomjs/","npm_config_sass_binary_site":"https://npm.taobao.org/mirrors/node-sass/"},"HostPathVolume":{"/var/lib/docker":"/var/lib/docker","/var/run/docker.sock":"/var/run/docker.sock"},"Ports":[8080,7575],"Replicas":1},"dockerAuthConfig":{"password":"Harbor12345","username":"unused"},"dockerFile":["FROM docker.vpclub.cn/hidevopsio/base-nodejs:8.12-alpine-0.0.1","COPY ./dist ${$APP_ROOT}/dist","USER 1001","EXPOSE 8080","CMD [\"http-server\", \"dist\"]"],"dockerRegistry":"docker-registry-default.app.vpclub.io","events":["createService","deployNode","clone","compile","buildImage","pushImage"]},"status":{"lastVersion":1}}
  clusterName: ""
  creationTimestamp: 2018-11-05T08:29:13Z
  generation: 0
  name: nodejs-8
  namespace: templates
  resourceVersion: "116854244"
  selfLink: /apis/mio.io/v1alpha1/namespaces/templates/buildconfigs/nodejs-8
  uid: e04355dd-e0d4-11e8-96de-005056935c80
spec:
  baseImage: docker.vpclub.cn/hidevopsio/nodejs:8.12-alpine-0.0.1
  cloneConfig:
    branch: master
    dstDir: /opt/app-root/src/vpclub
    url: https://gitlab.vpclub.cn
  codeType: nodejs
  compileCmd:
  - Script: npm install
    execType: script
  - Script: npm run build:dev
    execType: script
  - commandName: pwd
  deployData:
    Envs:
      APP_PROFILES_ACTIVE: local
      CODE_TYPE: nodejs
      DOCKER_API_VERSION: "1.24"
      npm_config_disturl: https://npm.taobao.org/dist/
      npm_config_electron_mirror: https://npm.taobao.org/mirrors/electron/
      npm_config_phantomjs_cdn: https://npm.taobao.org/dist/phantomjs/
      npm_config_sass_binary_site: https://npm.taobao.org/mirrors/node-sass/
    HostPathVolume:
      /var/lib/docker: /var/lib/docker
      /var/run/docker.sock: /var/run/docker.sock
    Ports:
    - 8080
    - 7575
    Replicas: 1
  dockerAuthConfig:
    password: Harbor12345
    username: unused
  dockerFile:
  - FROM docker.vpclub.cn/hidevopsio/base-nodejs:8.12-alpine-0.0.1
  - COPY ./dist ${APP_ROOT}/dist
  - USER 1001
  - EXPOSE 8080
  - CMD ["http-server", "dist"]
  dockerRegistry: docker-registry-default.app.vpclub.io
  events:
  - createService
  - deployNode
  - clone
  - compile
  - buildImage
  - pushImage
status:
  lastVersion: 1
