apiVersion: mio.io/v1alpha1
kind: DeploymentConfig
metadata:
  name: nodejs-8
  namespace: templates
spec:
  dockerRegistry: docker-registry.default.svc:5000
  env:
  - name: TZ
    value: Asia/Shanghai
  envType:
  - remoteDeploy
  - deploy
  fromRegistry: docker-registry-default.app.vpclub.io
  image: ""
  livenessProbe:
    exec:
      command:
      - curl
      - --silent
      - --show-error
      - --fail
      - http://localhost:8080/index.html
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
  nodeSelector:
    a: b
    c: d
  port:
  - containerPort: 8080
    name: tcp-8080
    protocol: TCP
  profile: dev
  readinessProbe:
    exec:
      command:
      - curl
      - --silent
      - --show-error
      - --fail
      - http://localhost:8080/index.html
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
status:
  lastVersion: 1
