apiVersion: mio.io/v1alpha1
kind: PipelineConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"mio.io/v1alpha1","kind":"PipelineConfig","metadata":{"annotations":{},"clusterName":"","creationTimestamp":"2018-10-15T08:12:49Z","generation":0,"name":"java","namespace":"templates","resourceVersion":"112781928","selfLink":"/apis/mio.io/v1alpha1/namespaces/templates/pipelineconfigs/java","uid":"1b3cbbc0-d052-11e8-b78c-005056935c80"},"spec":{"app":"","dockerRegistry":"","events":[{"eventTypes":"buildPipeline","name":"java"},{"eventTypes":"deploy","name":"java"},{"eventTypes":"service","name":"java"},{"eventTypes":"gateway","name":"java"}],"namespace":"","nodeSelector":"","profile":"dev","project":"","version":"v2"},"status":{}}
  clusterName: ""
  creationTimestamp: 2018-10-15T08:12:49Z
  generation: 0
  name: java
  namespace: templates
  resourceVersion: "113229339"
  selfLink: /apis/mio.io/v1alpha1/namespaces/templates/pipelineconfigs/java
  uid: 1b3cbbc0-d052-11e8-b78c-005056935c80
spec:
  app: ""
  dockerRegistry: ""
  events:
  - eventTypes: buildPipeline
    name: java
  - eventTypes: deploy
    name: java
  - eventTypes: service
    name: java
  - eventTypes: gateway
    name: java
  namespace: ""
  nodeSelector: ""
  profile: dev
  project: ""
  version: v2
status: {}
