// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CommandBuilder is an autogenerated mock type for the CommandBuilder type
type CommandBuilder struct {
	mock.Mock
}
