// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeploymentBuilder is an autogenerated mock type for the DeploymentBuilder type
type DeploymentBuilder struct {
	mock.Mock
}

// Update provides a mock function with given fields: name, namespace, event, phase
func (_m *DeploymentBuilder) Update(name string, namespace string, event string, phase string) error {
	ret := _m.Called(name, namespace, event, phase)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(name, namespace, event, phase)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
