// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PipelineBuilder is an autogenerated mock type for the PipelineBuilder type
type PipelineBuilder struct {
	mock.Mock
}

// Update provides a mock function with given fields: name, namespace, eventType, phase, eventVersion
func (_m *PipelineBuilder) Update(name string, namespace string, eventType string, phase string, eventVersion string) error {
	ret := _m.Called(name, namespace, eventType, phase, eventVersion)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) error); ok {
		r0 = rf(name, namespace, eventType, phase, eventVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
