// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import command "hidevops.io/mio/console/pkg/command"
import mock "github.com/stretchr/testify/mock"
import v1alpha1 "hidevops.io/mio/pkg/apis/mio/v1alpha1"

// DeploymentConfigAggregate is an autogenerated mock type for the DeploymentConfigAggregate type
type DeploymentConfigAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, pipelineName, namespace, sourceType, version, buildVersion, profile
func (_m *DeploymentConfigAggregate) Create(name string, pipelineName string, namespace string, sourceType string, version string, buildVersion string, profile string) (*v1alpha1.DeploymentConfig, error) {
	ret := _m.Called(name, pipelineName, namespace, sourceType, version, buildVersion, profile)

	var r0 *v1alpha1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string, string) *v1alpha1.DeploymentConfig); ok {
		r0 = rf(name, pipelineName, namespace, sourceType, version, buildVersion, profile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string, string) error); ok {
		r1 = rf(name, pipelineName, namespace, sourceType, version, buildVersion, profile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Template provides a mock function with given fields: cmd
func (_m *DeploymentConfigAggregate) Template(cmd *command.DeploymentConfig) (*v1alpha1.DeploymentConfig, error) {
	ret := _m.Called(cmd)

	var r0 *v1alpha1.DeploymentConfig
	if rf, ok := ret.Get(0).(func(*command.DeploymentConfig) *v1alpha1.DeploymentConfig); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DeploymentConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*command.DeploymentConfig) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
