// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import command "hidevops.io/mio/console/pkg/command"
import mock "github.com/stretchr/testify/mock"
import v1alpha1 "hidevops.io/mio/pkg/apis/mio/v1alpha1"

// GatewayConfigAggregate is an autogenerated mock type for the GatewayConfigAggregate type
type GatewayConfigAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, pipelineName, namespace, sourceType, version, profile
func (_m *GatewayConfigAggregate) Create(name string, pipelineName string, namespace string, sourceType string, version string, profile string) (*v1alpha1.GatewayConfig, error) {
	ret := _m.Called(name, pipelineName, namespace, sourceType, version, profile)

	var r0 *v1alpha1.GatewayConfig
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, string) *v1alpha1.GatewayConfig); ok {
		r0 = rf(name, pipelineName, namespace, sourceType, version, profile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.GatewayConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string, string) error); ok {
		r1 = rf(name, pipelineName, namespace, sourceType, version, profile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Gateway provides a mock function with given fields: gatewayConfig
func (_m *GatewayConfigAggregate) Gateway(gatewayConfig *v1alpha1.GatewayConfig) error {
	ret := _m.Called(gatewayConfig)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.GatewayConfig) error); ok {
		r0 = rf(gatewayConfig)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Template provides a mock function with given fields: cmd
func (_m *GatewayConfigAggregate) Template(cmd *command.GatewayConfig) (*v1alpha1.GatewayConfig, error) {
	ret := _m.Called(cmd)

	var r0 *v1alpha1.GatewayConfig
	if rf, ok := ret.Get(0).(func(*command.GatewayConfig) *v1alpha1.GatewayConfig); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.GatewayConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*command.GatewayConfig) error); ok {
		r1 = rf(cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
