// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import command "hidevops.io/mio/console/pkg/command"
import mock "github.com/stretchr/testify/mock"

// MioUpdateAggregate is an autogenerated mock type for the MioUpdateAggregate type
type MioUpdateAggregate struct {
	mock.Mock
}

// Add provides a mock function with given fields: name, update
func (_m *MioUpdateAggregate) Add(name string, update *command.MioUpdate) error {
	ret := _m.Called(name, update)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *command.MioUpdate) error); ok {
		r0 = rf(name, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: name
func (_m *MioUpdateAggregate) Delete(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: name
func (_m *MioUpdateAggregate) Get(name string) (*command.MioUpdate, error) {
	ret := _m.Called(name)

	var r0 *command.MioUpdate
	if rf, ok := ret.Get(0).(func(string) *command.MioUpdate); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.MioUpdate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
