// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "hidevops.io/mio/pkg/apis/mio/v1alpha1"

// NotifyAggregate is an autogenerated mock type for the NotifyAggregate type
type NotifyAggregate struct {
	mock.Mock
}

// Create provides a mock function with given fields: notify
func (_m *NotifyAggregate) Create(notify *v1alpha1.Notify) (*v1alpha1.Notify, error) {
	ret := _m.Called(notify)

	var r0 *v1alpha1.Notify
	if rf, ok := ret.Get(0).(func(*v1alpha1.Notify) *v1alpha1.Notify); ok {
		r0 = rf(notify)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Notify)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1alpha1.Notify) error); ok {
		r1 = rf(notify)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
