// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ReplicationControllerAggregate is an autogenerated mock type for the ReplicationControllerAggregate type
type ReplicationControllerAggregate struct {
	mock.Mock
}

// Delete provides a mock function with given fields: name, namespace
func (_m *ReplicationControllerAggregate) Delete(name string, namespace string) error {
	ret := _m.Called(name, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
